baseURL = 'https://tomregan.github.io/comparatorverifier/'
languageCode = 'en-gb'
title = 'Comparator Verifier'
theme = 'hugo-book'

disablePathToLower = true

[params]
BookToC = false
BookSearch = false

defaultContentLanguage = "en"
[languages]
[languages.en]
languageName = "English"
weight = 1
[languages.fr]
languageName = "Français"
weight = 2
[languages.pl]
languageName = "Polski"
weight = 3
[languages.bg]
languageName = "български"
weight = 4

[markup.goldmark.renderer]
unsafe = true