baseURL = 'https://tomregan.github.io/comparatorverifier/'
languageCode = 'en-gb'
title = 'Comparator Verifier'
theme = 'hugo-book'

disablePathToLower = true

[params]
BookToC = false
BookSearch = false

[markup.goldmark.renderer]
unsafe = true